foreground            #ff7500
background            #401010
selection_foreground  #ff7500
selection_background  #882500
url_color             #0d5cd6

# black
color0   #275050
color8   #70a090

# red
color1   #ff0000
color9   #fb4833

# green
color2   #20dd20
color10  #b8ba25

# yellow
color3   #ffaa00
color11  #fabc2e

# blue	
color4  #8888ff
color12 #8888ff

# magenta
color5   #ff40ff
color13  #aa20aa

# cyan
color6   #40ffff
color14  #20aaaa

# white
color7   #ffffff
color15  #aaaaaa
