[General]
closeToTray=false
networkCookies="@ByteArray(cc=lh18ZI0hcQ5k/PrwxyJBP4NvoDNQ3E124zvvbmTDs48sASNrF9G/dIWHRd1z9u8k2a0=; HttpOnly; expires=Tue, 01-Jun-2027 07:10:28 GMT; domain=localhost; path=/\n)"
startInTray=false
startupDelay=0
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x1\xdb\0\0\x3\xf8\0\0\0\0\0\0\0\0\0\0\x1\xdb\0\0\x3\xf8\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x1\xdb\0\0\x3\xf8)
zoomFactor=1
